# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
sudo: false

script:
  - travis_wait 60 R CMD check --as-cran --use-valgrind

# r_check_args: '--as-cran --use-valgrind'

addons:
  apt:
    packages:
      - valgrind

env:
  - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
  
