# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - oldrel
  - release
  - devel

r_github_packages: hadley/testthat

cache: packages

sudo: false

addons:
  apt:
    packages:
      - valgrind

env:
  - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
  - travis_wait 60 R CMD check --as-cran --use-valgrind iprior*tar.gz

script:
  - |
    R CMD build .

after_failure:
  - find *Rcheck -name '*.fail' -print -exec cat '{}' \;
