# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

cache: packages

sudo: false

r_github_packages: hadley/testthat

addons:
  apt:
    packages:
      - valgrind

matrix:
  include:
    - os: linux
      r: oldrel
      r_check_args: '--as-cran'

    - os: linux
      r: release
      env:
        - VALGRIND_OPTS='--leak-check=full --track-origins=yes'
      script:
        - |
          R CMD build .
          travis_wait 60 R CMD check --as-cran --use-valgrind iprior*tar.gz
      after_failure:
        - find *Rcheck -name '*.fail' -print -exec cat '{}' \;

    - os: linux
      r: devel
      r_check_args: '--as-cran'
